import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import { Header } from "@/shared/Header";

export const metadata: Metadata = {
  title: "Next pizza",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        <main className="min-h-screen"> {children}</main>
      </body>
    </html>
  );
}
